##**Código documentado**

In [1]:
#Importamos las librerías a utilizar
from google.colab import drive
import pandas as pd
import numpy as np

#Solicitamos permisos y montamos la carpeta de Google Drive  
drive.mount('/content/drive')

#Leemos el archivo
movies = pd.read_csv('/content/drive/MyDrive/Colab Notebooks/DataSets/datos_ejercicios/medias.csv', low_memory=False)

#Determinamos el 20% de las películas con más votos para establecer el mínimo de votos aceptados
votes_filter= movies['conteo'].quantile(0.80)

#Seleccionamos solo películas que tengan el  mínimo de votos aceptado
movies_filter = movies[movies.conteo >= votes_filter].reset_index()

#Calculamos el promedio del rating de las películas seleccionadas
media = movies_filter.media_rating.mean()

#Definimos una función con la fórmula a usar para el ranking
def media_RME(df, m=votes_filter, C=media):
    v = df['conteo']
    R = df['media_rating']
    # Calculamos el weighted score
    return round((R*v + C*m) / (v+m),2)

#Aplicamos la función a todo el dataset y creamos una nueva columna para almacenar el resultado
movies_filter["Puntuación"] = movies_filter.apply(media_RME,axis = 1)

#Establecemos un orden descendente  
movies_filter = movies_filter.sort_values('Puntuación', ascending=False)

#Mostramos las mejores 25 películas y renombramos los nombres de las columnas.
movies_filter[['imdb_title', 'conteo', 'media_rating', 'Puntuación']].rename(
   columns={'imdb_title':'Título', 'conteo':'Cantidad de Votos','media_rating':'Promedio de Votos'}).head(25)

Mounted at /content/drive

                                             Título  ...  Puntuación
7306                                    Be Somebody  ...        9.90
4808                            MSG 2 the Messenger  ...        9.44
7762                       The Shawshank Redemption  ...        9.37
7366  The Lord of the Rings: The Return of the King  ...        9.28
7642                                The Dark Knight  ...        9.25
7693                                   12 Angry Men  ...        9.18
3451                 Avengers: Age of Ultron Parody  ...        9.15
7353                         The Godfather: Part II  ...        9.08
7845                                          Joker  ...        9.07
6864                      Demon Slayer: Mugen Train  ...        9.06
7279                          It's a Wonderful Life  ...        9.06
7253                                        Amadeus  ...        9.04
7796                              Avengers: Endgame  ...        9.03
7334                 The Good, the Bad and the Ugly  ...        9.02
7632                                  The Godfather  ...        9.02
7066                     Terminator 2: Judgment Day  ...        9.02
2788                                   Five Minutes  ...        9.00
7713                                   Forrest Gump  ...        9.00
7746                                      Inception  ...        9.00
7522                                 The Green Mile  ...        8.98
7468                               Schindler's List  ...        8.98
7545                               Scent of a Woman  ...        8.96
7351                                         Dangal  ...        8.91
6869                              Bajrangi Bhaijaan  ...        8.91
7613                               A Beautiful Mind  ...        8.90

[25 rows x 4 columns]